---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Ashrith2727/DevPlatform.git
    targetRevision: main
    path: namespaces
  destination:
    server: https://kubernetes.default.svc
    namespace: develop
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
