---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: developer-binding
  namespace: develop
subjects:
  - kind: Group
    name: developers
roleRef:
  kind: Role
  name: developer
  apiGroup: rbac.authorization.k8s.io
