---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: readonly-binding
  namespace: production
subjects:
  - kind: Group
    name: developers
roleRef:
  kind: Role
  name: readonly
  apiGroup: rbac.authorization.k8s.io
